### ISSUE TITLE
Add a default value for `pod.dashboard_url`

### ISSUE THREAD

**Issue by RemiBardon** [prose-im/prose-pod-api#269]
In #268 I introduce new configuration keys, but because of the way serde parses it I have to make `pod.dashboard_url` a required key:

```toml
[pod]
address = { domain = "prose.test.org" }
dashboard_url = "http://admin.prose.test.org"
```

We could add a default value of `https://admin.{pod.address.hostname}` if `pod.address.hostname` is set or `https://{pod.address.ipv(4|6)}:3030` otherwise.

It might be trickier than expected and might surprise users so let’s keep `pod.dashboard_url` required at the moment.
